apiVersion: v1
kind: Service
metadata:
  name: posts-cluster-ip
spec:
  selector:
    app: posts
  type: ClusterIP
  ports:
    - name: posts-port
      port: 4000
      targetPort: 4000
      protocol: TCP