apiVersion: skaffold/v2beta28
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: beretedocker/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '*.js'
    - image: beretedocker/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '*.js'
    - image: beretedocker/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '*.js'
    - image: beretedocker/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '*.js'
    - image: beretedocker/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '*.js'
    - image: beretedocker/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: src/**/*.js