apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deployment
spec:
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: beretedocker/comments
          resources:
            requests:
              memory: 128Mi
              cpu: 500m
            limits:
              memory: 256Mi
              cpu: "1"