apiVersion: v1
kind: Service
metadata:
  name: event-bus-cluster-ip
spec:
  selector:
    app: event-bus
  type: ClusterIP
  ports:
    - name: event-bus-port
      protocol: TCP
      port: 4005
      targetPort: 4005