apiVersion: v1
kind: Service
metadata:
  name: query-cluster-ip
spec:
  selector:
    app: query
  type: ClusterIP
  ports:
    - name: query-port
      port: 4002
      targetPort: 4002
      protocol: TCP